name: PowermageCore
version: '${project.version}'
main: org.distantnetwork.powermagecore.PowermageCore
api-version: 1.18
authors: [ JakeyGilly, Explorer017, CaptainATW, InvernessBlock ]
description: The Core Plugin For Powermage
commands:
  discord:
    usage: /discord
    description: Opens the Discord Server
  store:
    usage: /store
    description: Opens the Store
    aliases:
      - ranks
  menu:
    usage: /menu
    description: Opens the Menu
  spawn:
    usage: /spawn
    description: Opens the Spawn Menu
  class:
    usage: /class
    description: Selects your class
  soulshop:
    usage: /soulshop
    description: Opens the Soulshop
  giveitem:
    usage: /giveitem itemid
    description: Gives an CustomItem to a Player
  upgrade:
    usage: /upgrade
    description: Opens the Upgrade Menu
  powermage:
    usage: /powermage
    description: Opens the Powermage Menu
    aliases:
      - pmc
      - powermage
      - powermagecore
      - pm
  givecoins:
    usage: /givecoins <player> amount
    description: Gives Coins to a Player
    aliases:
      - givemoney
      - givecoin
  givesouls:
    usage: /givesouls <player> amount
    description: Gives Souls to a Player
    aliases:
      - givesoul
  setupgrades:
    usage: /setupgrades
    description: Opens the Setup Upgrade Menu
  levelup:
    description: Opens the Levelup Menu
    aliases:
      - lvlup
    usage: /levelup [player] [amount]
  setcombatlog:
    usage: /setcombatlog
    description: Sets the CombatLog
    usage: /setcombatlog <true/false/on/off>

